FROM node:20

WORKDIR /app

ARG DATABASE_URL
ENV NODE_ENV=development
ENV DATABASE_URL=${DATABASE_URL}

COPY package.json package-lock.json ./
RUN npm install --include=dev

COPY . .

RUN npx prisma generate --schema=prisma/schema.prisma

EXPOSE 3000
CMD ["npm", "run", "start"]